// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bank is the predicate function for bank builders.
type Bank func(*sql.Selector)

// LoanApplication is the predicate function for loanapplication builders.
type LoanApplication func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
