// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Arlandaren/easyfund/ent/loanapplication"
	"github.com/Arlandaren/easyfund/ent/schema"
	"github.com/Arlandaren/easyfund/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	loanapplicationFields := schema.LoanApplication{}.Fields()
	_ = loanapplicationFields
	// loanapplicationDescCreatedAt is the schema descriptor for created_at field.
	loanapplicationDescCreatedAt := loanapplicationFields[7].Descriptor()
	// loanapplication.DefaultCreatedAt holds the default value on creation for the created_at field.
	loanapplication.DefaultCreatedAt = loanapplicationDescCreatedAt.Default.(func() time.Time)
	// loanapplicationDescUpdatedAt is the schema descriptor for updated_at field.
	loanapplicationDescUpdatedAt := loanapplicationFields[8].Descriptor()
	// loanapplication.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	loanapplication.DefaultUpdatedAt = loanapplicationDescUpdatedAt.Default.(func() time.Time)
	// loanapplication.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	loanapplication.UpdateDefaultUpdatedAt = loanapplicationDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
