// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Arlandaren/easyfund/ent/bank"
	"github.com/Arlandaren/easyfund/ent/predicate"
)

// BankUpdate is the builder for updating Bank entities.
type BankUpdate struct {
	config
	hooks    []Hook
	mutation *BankMutation
}

// Where appends a list predicates to the BankUpdate builder.
func (_u *BankUpdate) Where(ps ...predicate.Bank) *BankUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BankUpdate) SetName(v string) *BankUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BankUpdate) SetNillableName(v *string) *BankUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *BankUpdate) SetRating(v float64) *BankUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *BankUpdate) SetNillableRating(v *float64) *BankUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *BankUpdate) AddRating(v float64) *BankUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *BankUpdate) ClearRating() *BankUpdate {
	_u.mutation.ClearRating()
	return _u
}

// Mutation returns the BankMutation object of the builder.
func (_u *BankUpdate) Mutation() *BankMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BankUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BankUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BankUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BankUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BankUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bank.Table, bank.Columns, sqlgraph.NewFieldSpec(bank.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bank.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(bank.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(bank.FieldRating, field.TypeFloat64, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(bank.FieldRating, field.TypeFloat64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bank.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BankUpdateOne is the builder for updating a single Bank entity.
type BankUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BankMutation
}

// SetName sets the "name" field.
func (_u *BankUpdateOne) SetName(v string) *BankUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BankUpdateOne) SetNillableName(v *string) *BankUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *BankUpdateOne) SetRating(v float64) *BankUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *BankUpdateOne) SetNillableRating(v *float64) *BankUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *BankUpdateOne) AddRating(v float64) *BankUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *BankUpdateOne) ClearRating() *BankUpdateOne {
	_u.mutation.ClearRating()
	return _u
}

// Mutation returns the BankMutation object of the builder.
func (_u *BankUpdateOne) Mutation() *BankMutation {
	return _u.mutation
}

// Where appends a list predicates to the BankUpdate builder.
func (_u *BankUpdateOne) Where(ps ...predicate.Bank) *BankUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BankUpdateOne) Select(field string, fields ...string) *BankUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Bank entity.
func (_u *BankUpdateOne) Save(ctx context.Context) (*Bank, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BankUpdateOne) SaveX(ctx context.Context) *Bank {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BankUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BankUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BankUpdateOne) sqlSave(ctx context.Context) (_node *Bank, err error) {
	_spec := sqlgraph.NewUpdateSpec(bank.Table, bank.Columns, sqlgraph.NewFieldSpec(bank.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bank.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bank.FieldID)
		for _, f := range fields {
			if !bank.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bank.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bank.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(bank.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(bank.FieldRating, field.TypeFloat64, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(bank.FieldRating, field.TypeFloat64)
	}
	_node = &Bank{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bank.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
